FROM useparagon/ts-node:1.02

# update packages
#RUN apk update

# create root application folder
WORKDIR /app

# copy configs to /app folder
COPY package*.json ./
COPY tsconfig.json ./
# copy source code to /app/src folder
COPY src /app/src

# check files list
RUN ls -a

RUN npm install
#RUN npm run build

EXPOSE 5000

CMD [ "npm", "run","dev" ]