version: '3.8'
services:
  app:
    container_name: goalyn-backend
    restart: always
    build:
      context: ./
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*